### ISSUE TITLE
Add functionality for parameter combinations

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-tests#2]
Based on #1, it would be very good if the testing infrastructure supported parameter combinations. Then one wouldn't end up with as many test-* files as there are parameter combinations. Also I need to set the epsilon on a parameter basis, this would be nice too.

**Comment by tfarago** [comment]
there could be e.g. `test-measure.sh` and `test-measure.config` file with all the parameter combinations and the `test-measure.sh` would be called with the parameters on input. E.g. for the measure the config would be:
```
axis: -1 0 1
metric: min max sum ...
```
and then the test would be called with `test-measure.sh metric axis`. In the config file could also be the epsilon settings, e.g.:
```
epsilon default: 0.001
epsilon kurtosis: 0.1
```

**Comment by matze** [comment]
Sounds alright, let me give a few minutes to think about this.

**Comment by matze** [comment]
So, I changed the structure similar to how `tomoperf` behaves, i.e. all tests are listed in a JSON file. The only downside I see is that one cannot run an individual test on its own. I think I covered all your use cases (parameter matrix, epsilon per parameter) but if there's something left, let me know. And don't look to deep into the code, it's a bit embarrassing … :smile:

**Comment by tfarago** [comment]
Hmm, looks quite good already. I just need to be able to access the `reference` inside the test and I will be good to go. I need that to set up the reference on the fly.

**Comment by matze** [comment]
Well you can specify whatever you want in the test, add a Python or shell script to the repo which does both set up and test run and just call that. But if you find this to be unclean I could add an `entry` key which just prepares things.

**Comment by tfarago** [comment]
Well the `entry` thing would be good, there should actually be `entry` and `exit` options but I don't need that now. The point is that I want to generate the reference on-the-fly and its name is currently computed by the runner and not passed to the test itself and I don't want to do any magic regarding determining the reference name the runner expects.

**Comment by matze** [comment]
> its name is currently computed by the runner and not passed to the test itself

Well, you could've just asked for this :smile: It's now possible to access `${reference}` for whatever purpose.

**Comment by tfarago** [comment]
Grazie.

**Comment by matze** [comment]
Should be done with the last commits.
